services:
  aws:
    container_name: aws
    image: withfresh/aws-linux:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${RDS_URL}

      - SPRING_DATASOURCE_USERNAME=${RDS_USERNAME}

      - SPRING_DATASOURCE_PASSWORD=${RDS_PASSWORD}